#+Title: Daily Quiet Time Bible Study
 
* June 04, 2021: JOHN 1: THE MASTER & FIVE WHO FOLLOWED

For more context before you begin studying, read this introduction to the book of John. 

It was a great day in our history when a man first walked on the moon. But the Bible declares that a far greater event took place two thousand years ago. God walked on the earth in the person of Jesus Christ. John opens his Gospel with a beautiful hymn of exaltation to Christ. It is one of the most profound passages in all the Bible. It is written in simple, straightforward language, yet in studying the depths of its meaning, it is a passage where we never reach bottom. It is an ocean-sized truth, and we have to be content to paddle around in shallow water.

** Warming Up to God

 Consider the miracle of God becoming human. Give him your praise and worship for what he has done for you.

 Read John 1

 
** Discovering the Word

- John records more than a dozen names or descriptions of Jesus in this chapter. What are some of these?
- In verses 1-3 what facts does John declare to be true of the Word?
- According to verses 14-18, what specific aspects of God's character are revealed to us through Jesus?
- What steps did John take to guarantee that people would not look at him but at Christ?
- In verses 35-51 we are introduced to five men: Andrew, Simon, Philip, Nathanael and one unnamed disciple (John). How did each man respond to the testimony he heard about Jesus?


** Applying the Word

- Which of the names of Jesus has the most significance to you personally? Explain why.

- What do you hope will happen in your life as a result of studying the Gospel of John?
  
** Responding in Prayer

-  Ask God to bring the light and life of Jesus to you as you study his Word.
